"""Reproducible CC0 brush-tip conversion; run with the downloaded January 2023 bundle.

Requires Pillow. Krita paint engines are not emulated: these are sampled native tips.
Animated GIH brushes expose their first frame explicitly; original assets are retained.
"""
import hashlib, io, json, pathlib, struct, sys, zipfile
from PIL import Image, ImageOps, ImageChops

root = pathlib.Path(__file__).resolve().parents[1]
source = pathlib.Path(sys.argv[1])
out = root / 'native/assets/brushes/deevad-2023'
out.mkdir(parents=True, exist_ok=True)
z = zipfile.ZipFile(source)
records = []
rust = []

def gbr(data):
    header, version, w, h, channels = struct.unpack('>IIIII', data[:20])
    assert version in (1, 2) and channels in (1, 4) and w*h < 10000000
    raw = data[header:header+w*h*channels]
    im = Image.frombytes('L' if channels == 1 else 'RGBA', (w,h), raw)
    # GIMP grayscale tips already use white as full coverage.
    return im if channels == 1 else im.getchannel('A')

for name in sorted(z.namelist()):
    if not name.startswith('brushes/'): continue
    data = z.read(name)
    filename = pathlib.PurePosixPath(name).name
    (out/filename).write_bytes(data)
    if name.endswith('.png'):
        im = Image.open(io.BytesIO(data)).convert('RGBA')
        coverage = ImageChops.multiply(ImageOps.invert(im.convert('L')), im.getchannel('A'))
    elif name.endswith('.gbr'): coverage = gbr(data)
    elif name.endswith('.gih'):
        offset = data.index(b'\n', data.index(b'\n')+1)+1
        coverage = gbr(data[offset:])
    else: continue
    coverage.thumbnail((192,192), Image.Resampling.LANCZOS)
    rawname = pathlib.Path(filename).stem+'.tip'
    (out/rawname).write_bytes(coverage.tobytes())
    label = pathlib.Path(filename).stem.replace('_',' ').replace('-',' ')
    if name.endswith('.gih'): label += ' (frame 1)'
    rust.append(f'    ("Deevad · {label}", {coverage.width}, {coverage.height}, include_bytes!("../../../assets/brushes/deevad-2023/{rawname}")),')
    records.append({'source':name,'sha256':hashlib.sha256(data).hexdigest(),'tip':rawname,'width':coverage.width,'height':coverage.height,'tip_sha256':hashlib.sha256(coverage.tobytes()).hexdigest(),'conversion':'first frame' if name.endswith('.gih') else 'static tip'})
(out/'manifest.json').write_text(json.dumps({'author':'David Revoy','license':'CC0-1.0','url':'https://www.davidrevoy.com/article953/krita-brushes-2023-01-bundle','download':'https://www.peppercarrot.com/extras/resources/deevad-bundle_23-01.zip','bundle_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'assets':records},indent=2),encoding='utf-8')
(root/'native/crates/paint/src/coskit_tips.rs').write_text('// Generated by scripts/import-deevad-brushes.py. CC0 tips by David Revoy.\n#[allow(clippy::type_complexity)]\npub const TIPS: &[(&str, u32, u32, &[u8])] = &[\n'+'\n'.join(rust)+'\n];\n',encoding='utf-8')
print(f'Converted {len(records)} source tips; provenance and original assets retained.')
