Unicode True
!include "MUI2.nsh"
Name "CosKit ${VERSION}"
OutFile "${OUTFILE}"
InstallDir "$LOCALAPPDATA\Programs\CosKitStudio"
RequestExecutionLevel user
SetCompressor /SOLID lzma
!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "..\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "English"
Section "CosKit"
  SetOutPath "$INSTDIR"
  File "${STAGE}\coskit.exe"
  File "${STAGE}\coskit-cli.exe"
  File "${STAGE}\native-studio-guide.md"
  File "${STAGE}\native-release.md"
  File "${STAGE}\ACKNOWLEDGEMENTS.md"
  File "${STAGE}\p0-performance.md"
  File "${STAGE}\p1-harness-and-review.md"
  File "${STAGE}\getting-started-v1.md"
  File "${STAGE}\release-1.0.0.md"
  ; Remove only obsolete documentation shipped by earlier CosKit releases.
  Delete "$INSTDIR\photocraft-feature-matrix.md"
  Delete "$INSTDIR\v1-photocraft-parity-plan.md"
  File "${STAGE}\coskit-mcp.md"
  File "${STAGE}\autonomous-retouch-harness.md"
  File "${STAGE}\ckpipe-project-format.md"
  File "${STAGE}\beta4-validation.md"
  File "${STAGE}\fluent-workspace.md"
  File "${STAGE}\cosplay-validation.md"
  SetOutPath "$INSTDIR\scripts"
  File "${STAGE}\scripts\start-coskit-mcp.ps1"
  SetOutPath "$INSTDIR\licenses"
  File "${STAGE}\licenses\*.txt"
  File "${STAGE}\licenses\*.md"
  CreateShortcut "$SMPROGRAMS\CosKit Studio.lnk" "$INSTDIR\coskit.exe"
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\CosKitStudio" "DisplayName" "CosKit Studio ${VERSION}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\CosKitStudio" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\CosKitStudio" "UninstallString" '"$INSTDIR\Uninstall.exe"'
SectionEnd
Section "Uninstall"
  Delete "$SMPROGRAMS\CosKit Studio.lnk"
  Delete "$INSTDIR\coskit.exe"
  Delete "$INSTDIR\coskit-cli.exe"
  Delete "$INSTDIR\native-studio-guide.md"
  Delete "$INSTDIR\native-release.md"
  Delete "$INSTDIR\ACKNOWLEDGEMENTS.md"
  Delete "$INSTDIR\p0-performance.md"
  Delete "$INSTDIR\p1-harness-and-review.md"
  Delete "$INSTDIR\getting-started-v1.md"
  Delete "$INSTDIR\release-1.0.0.md"
  Delete "$INSTDIR\photocraft-feature-matrix.md"
  Delete "$INSTDIR\v1-photocraft-parity-plan.md"
  Delete "$INSTDIR\coskit-mcp.md"
  Delete "$INSTDIR\autonomous-retouch-harness.md"
  Delete "$INSTDIR\ckpipe-project-format.md"
  Delete "$INSTDIR\beta4-validation.md"
  Delete "$INSTDIR\fluent-workspace.md"
  Delete "$INSTDIR\cosplay-validation.md"
  Delete "$INSTDIR\scripts\start-coskit-mcp.ps1"
  RMDir "$INSTDIR\scripts"
  Delete "$INSTDIR\licenses\CosKit-MIT.txt"
  Delete "$INSTDIR\licenses\PhotoCraft-MIT.txt"
  Delete "$INSTDIR\licenses\PhotoCraft-Apache.txt"
  Delete "$INSTDIR\licenses\PhotoCraft-NOTICE.txt"
  Delete "$INSTDIR\licenses\ATTRIBUTION.md"
  Delete "$INSTDIR\licenses\THIRD_PARTY_NOTICES.md"
  Delete "$INSTDIR\licenses\LICENSE-lucide.txt"
  Delete "$INSTDIR\licenses\LICENSE-noun-magnetic-lasso.txt"
  Delete "$INSTDIR\licenses\LICENSE-SCOWL.txt"
  Delete "$INSTDIR\licenses\LICENSE-translations.txt"
  Delete "$INSTDIR\licenses\PhotoCraft-icon-LICENSE.txt"
  Delete "$INSTDIR\licenses\Deevad-CC0.txt"
  Delete "$INSTDIR\licenses\Deevad-brushes.md"
  RMDir "$INSTDIR\licenses"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\CosKitStudio"
SectionEnd
