// Generated by scripts/import-deevad-brushes.py. CC0 tips by David Revoy.
#[allow(clippy::type_complexity)]
pub const TIPS: &[(&str, u32, u32, &[u8])] = &[
    ("Deevad · 3 rake", 150, 150, include_bytes!("../../../assets/brushes/deevad-2023/3_rake.tip")),
    ("Deevad · abominable snowman", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/abominable_snowman.tip")),
    ("Deevad · bristle", 54, 52, include_bytes!("../../../assets/brushes/deevad-2023/bristle.tip")),
    ("Deevad · bristles circle medium", 192, 187, include_bytes!("../../../assets/brushes/deevad-2023/bristles_circle_medium.tip")),
    ("Deevad · bristles grouped", 64, 64, include_bytes!("../../../assets/brushes/deevad-2023/bristles_grouped.tip")),
    ("Deevad · chalk chisel losange 202210A (frame 1)", 64, 64, include_bytes!("../../../assets/brushes/deevad-2023/chalk_chisel_losange_202210A.tip")),
    ("Deevad · chalk chisel random small (frame 1)", 64, 64, include_bytes!("../../../assets/brushes/deevad-2023/chalk_chisel_random_small.tip")),
    ("Deevad · chalk sparse", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/chalk_sparse.tip")),
    ("Deevad · chisel streaks", 150, 150, include_bytes!("../../../assets/brushes/deevad-2023/chisel_streaks.tip")),
    ("Deevad · deevad 202210C compact fix (frame 1)", 180, 124, include_bytes!("../../../assets/brushes/deevad-2023/deevad-202210C_compact-fix.tip")),
    ("Deevad · deevad painterly brush tip 2023C", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/deevad-painterly-brush-tip_2023C.tip")),
    ("Deevad · flat tip dirty", 153, 64, include_bytes!("../../../assets/brushes/deevad-2023/flat-tip-dirty.tip")),
    ("Deevad · impressionism brush (frame 1)", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/impressionism_brush.tip")),
    ("Deevad · random debris", 153, 64, include_bytes!("../../../assets/brushes/deevad-2023/random-debris.tip")),
    ("Deevad · rock pitted fixed (frame 1)", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/rock_pitted-fixed.tip")),
    ("Deevad · scratches rough (frame 1)", 192, 192, include_bytes!("../../../assets/brushes/deevad-2023/scratches_rough.tip")),
    ("Deevad · splat dots", 112, 111, include_bytes!("../../../assets/brushes/deevad-2023/splat_dots.tip")),
    ("Deevad · splats large (frame 1)", 192, 174, include_bytes!("../../../assets/brushes/deevad-2023/splats_large.tip")),
    ("Deevad · square rough lightgrey", 192, 189, include_bytes!("../../../assets/brushes/deevad-2023/square_rough_lightgrey.tip")),
];
